#!/bin/bash

set -eux

if [ ! -t 1 ] ; then
	# Real ControlPlane
	exec >> /tmp/controlplane-enter.log 2>&1
	cd "$( dirname $0 )"
else
	# Emulate ControlPlane
	PATH=/usr/bin:/bin:/usr/sbin:/sbin
fi



current_network_location() {
	scselect | perl -lne '
	  /^ \* .*\s\((.*)\)$/ and print $1
	'
}

current_controlplane_context() {
	osascript -e 'tell application "ControlPlane" to get current context'
}

svc() {
	sudo /usr/local/bin/svc "$@"
}

switch_comment_blocks() {
	env LOC="$1" perl -i ./switch-comment-blocks \
		"$( realpath ~/.curlrc )" \
		"$( realpath ~/.ssh/config )" \
		"$( realpath ~/.subversion/servers )" \
		;
}



current_context="${1:-$( current_controlplane_context )}"
echo "$( date ) controlplane current_context=$current_context"

# For "realpath"
export PATH=$PATH:$HOME/git/github.com/rvedotrc/misc-scripts/bin

case "$current_context" in
	"Min lejlighed")
		scselect "$current_context"
		switch_comment_blocks Home
		svc -d $HOME/services/openvpn-tinytoucan
		rm -f bashrc ; ln -s bashrc.null bashrc
		;;
	"Reith netværk")
		scselect "$current_context"
		switch_comment_blocks Reith
		svc -tu $HOME/services/openvpn-tinytoucan
		rm -f bashrc ; ln -s bashrc.Reith bashrc
		;;
	*)
		scselect "Andet netværk"
		switch_comment_blocks Andet
		svc -d $HOME/services/openvpn-tinytoucan
		rm -f bashrc ; ln -s bashrc.null bashrc
		;;
esac

# eof
