#!/bin/bash

exec >> /tmp/t.log 2>&1
set -x

exec > >(
	exec /usr/local/bin/multilog t /Users/rachel/git/thomas.rudolf.org.uk/network-location-change/log/main
) 2>&1

set -eu
MYDIR="$( dirname "$0" )"
cd "$MYDIR"

printenv > ./last-env

# For realpath
export PATH=/Users/rachel/git/github.com/rvedotrc/misc-scripts/bin:$PATH

svc() {
	sudo /usr/local/bin/svc "$@"
}

firefox_proxy_type() {
	pushd ~/Library/Application\ Support/Firefox/Profiles/5xdcg2fi.default >/dev/null
	local N

	N=$1 perl -i -wpe '
		s/\(("network.proxy.type"), \d+\)/($1, $ENV{N})/;
	' prefs.js
	# Alas so far I haven't found a way to persuade Firefox to reload the
	# config via an external trigger, so all this does is means that /if/
	# Firefox restarts, it'll start with the correct config.

	popd >/dev/null
}

set_tsocks() {
	local LOC=$1

	local CONF=tsocks.conf.null
	if [ -f "tsocks.conf.$LOC" ] ; then
		CONF=tsocks.conf.$LOC
	fi

	local EXISTING="$( readlink tsocks.conf || : )"
	if [ "$EXISTING" != "$CONF" ] ; then
		rm -f tsocks.conf
		ln -s $CONF tsocks.conf
	fi
}

switch_comment_blocks() {
	env LOC="$1" perl -i ./switch-comment-blocks \
		"$( realpath ~/.curlrc )" \
		"$( realpath ~/.ssh/config )" \
		"$( realpath ~/.subversion/servers )" \
		;
}

maven_reith_cache() {
	./with-rvm ./maven-set-proxy-active ./maven-settings.xml www-cache.reith.bbc.co.uk "$1"
}

LOC="${1:-$( ./get-location )}"

FF_PROXY_TYPE_MANUAL=1
FF_PROXY_TYPE_PAC=2
FF_PROXY_TYPE_AUTO=4

case "$LOC" in
	Home)
		firefox_proxy_type $FF_PROXY_TYPE_AUTO
		switch_comment_blocks "$LOC"
		maven_reith_cache false
		svc -d $HOME/svscan/openvpn-brunel
		;;
	Reith)
		firefox_proxy_type $FF_PROXY_TYPE_PAC
		switch_comment_blocks "$LOC"
		maven_reith_cache true
		svc -tu $HOME/svscan/openvpn-brunel
		;;
	Roaming)
		firefox_proxy_type $FF_PROXY_TYPE_AUTO
		switch_comment_blocks "$LOC"
		maven_reith_cache false
		svc -d $HOME/svscan/openvpn-brunel
		;;
	*)
		echo "$0: unknown location $LOC" >&2
		exit 1
		;;
esac

set_tsocks "$LOC"

if [ -f "bashrc.$LOC" ] ; then
	rm -f bashrc ; ln -s bashrc.$LOC bashrc
else
	rm -f bashrc ; ln -s bashrc.null bashrc
fi

svc -k $HOME/svscan/socks-proxy
svc -k $HOME/svscan/forge-irc

sleep 1
sudo /usr/local/bin/svstat /Users/rachel/svscan/*

exit
