#!/bin/bash

set -eu
cd "$( dirname "$0" )"

switch_comment_blocks() {
	env LOC="$1" perl -i ./switch-comment-blocks \
		"$( realpath ~/.curlrc )" \
		"$( realpath ~/.ssh/config )" \
		"$( realpath ~/.subversion/servers )" \
		;
}

LOC="${1:-$( ./get-location )}"

case "$LOC" in
	Home)
		switch_comment_blocks "$LOC"
		;;
	Reith)
		switch_comment_blocks "$LOC"
		;;
	Roaming)
		switch_comment_blocks "$LOC"
		;;
	*)
		echo "$0: unknown location $LOC" >&2
		exit 1
		;;
esac
